export const data = {
	itemType: [
	  { id: 1, type: 'breakfast' },
	  { id: 2, type: 'lunch' },
	  { id: 3, type: 'dinner' },
	  { id: 4, type: 'snacks' }
	],
  
	item: [
	  {
		title: 'Egg sauce',
		img: '/img/b1.jpg',
		description: 'Egg sauce is typically one of Nigeria\'s staple foods, perfect for breakfast.',
		price: '₺1500',
		type: 1,
		id: 1,
	  },
	  {
		title: 'Abacha',
		img: '/img/lm5.jpg',
		description: 'African salad is native to the ndi Igbo people.',
		price: '₺3000',
		type: 2,
		id: 2,
	  },
	  {
		title: 'Boiled Potatoes',
		img: '/img/dm1.jpg',
		description: 'Boiled potatoes are highly nutritious, suitable for kids and everyone, containing fiber.',
		price: '₺1000',
		type: 3,
		id: 3,
	  },
	  {
		title: 'Grilled plantain',
		img: '/img/sm3.jpg',
		description: 'Grilled plantains, commonly called "bole in Nigeria," are eaten with roasted groundnut, smoked fish, palm oil, and pepper sauce.',
		price: '₺300',
		type: 4,
		id: 4,
	  },
	  {
		title: 'Akara and Pap',
		img: '/img/b2.jpg',
		description: 'Akara and Pap is a popular weekend morning meal in Nigeria due to its light and filling nature.',
		price: '₺300',
		type: 1,
		id: 5,
	  },
	  {
		title: 'Pounded yam and egusi soup',
		img: '/img/lm3.jpg',
		description: 'Pounded yam and egusi is a very delicious meal.',
		price: '₺2000',
		type: 2,
		id: 6,
	  },
	  {
		title: 'Spaghetti',
		img: '/img/dm3c.jpg',
		description: 'Spaghetti is a starchy pasta of Italian origin made in the form of long strings, boiled, and served with a variety of sauces.',
		price: '₺1500',
		type: 3,
		id: 7,
	  },
	  {
		title: 'Puff Puff',
		img: '/img/sm2.jpg',
		description: 'Puff Puff, a traditional African snack made of fried dough, is popular in Nigeria, Sierra Leone, Ghana, and Anglophone Cameroon.',
		price: '₺200',
		type: 4,
		id: 8,
	  },
	  {
		title: 'Toast Bread and Tea',
		img: '/img/b3.jpg',
		description: 'Most homes in Nigeria love their bread toasted, served with sauce, or enjoyed with hot tea or chocolate drink.',
		price: '₺1000',
		type: 1,
		id: 9,
	  },
	  {
		title: 'Jollof rice',
		img: '/img/lm1.jpg',
		description: 'Jollof rice is a popular West African dish widely enjoyed.',
		price: '₺2000',
		type: 2,
		id: 10,
	  },
	  {
		title: 'Boiled plantain',
		img: '/img/dm4a.jpg',
		description: 'Boiled plantains are highly nutritious and can be served with different sauces.',
		price: '₺2000',
		type: 3,
		id: 11,
	  },
	  {
		title: 'Corn',
		img: '/img/sm4.jpg',
		description: 'Corn is highly nutritious and can be eaten roasted, boiled, or with coconut and pear.',
		price: '₺500',
		type: 4,
		id: 12,
	  },
	],
  };
  